#!/bin/bash

#SBATCH -J e_const
#SBATCH -o mpi_%j.txt
#SBATCH -e mpi_%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=10
#SBATCH --time=00:30:00

cd /directory/with/stuff

ensemble_folder="/dartfs-hpc/scratch/f002bx6/adage_models/ensemble_models"
data_compendium="/dartfs-hpc/scratch/f002bx6/adage_models/pao1_aligned_rnaseq_compendium_zp2_MRnorm_log_01_byall.csv"
model_size=300
scratch_folder='/dartfs-hpc/scratch/f002bx6'

srun Rscript ensemble_construction_p.R $data_compendium \
../outputs/e_models/$model_size/ $scratch_folder $model_size \
660 735 1 weighted $ensemble_folder /dartfs-hpc/scratch/f002bx6/adage_models/net${model_size}_weighted_cor.txt;
